from dataclasses import dataclass


@dataclass
class ChessSquare:
    rank: int
    file: str

    # Autogenerated __eq__ doesn't seem to work for some reason so overriding
    def __eq__(self, other):
        return self.rank == other.rank and self.file == other.file


def from_string(square_str):
    rank = int(square_str[1])
    file = square_str[0]
    return ChessSquare(rank, file)


def compare_squares(a, b):
    rank_a = a.rank()
    rank_b = b.rank()
    if not rank_a == rank_b:
        return rank_a - rank_b
    else:
        file_a_ord = ord(a.file())
        file_b_ord = ord(b.file())
        return file_a_ord - file_b_ord
